data <- read.csv("results-survey254952.csv")
data2 <-read.csv("results-survey129171.csv")
srednieprimharmprim <-numeric()
srednieprimharmprim[1] <- mean(c(data$PRIMHARMPRIMSUWAK.1., data$PRIMHARMPRIMSUWAK.1..1), na.rm = TRUE)
srednieprimharmprim[2] <- mean(c(data$PRIMHARMPRIMSUWAK.2., data$PRIMHARMPRIMSUWAK.2..1), na.rm = TRUE)
srednieprimharmprim[3] <- mean(c(data$PRIMHARMPRIMSUWAK.3., data$PRIMHARMPRIMSUWAK.3..1), na.rm = TRUE)
srednieprimharmprim[4] <- mean(c(data$PRIMHARMPRIMSUWAK.4., data$PRIMHARMPRIMSUWAK.4..1), na.rm = TRUE)
srednieprimharmprim[5] <- mean(c(data$PRIMHARMPRIMSUWAK.5., data$PRIMHARMPRIMSUWAK.5..1), na.rm = TRUE)

srednieprimharmbis <-numeric()
srednieprimharmbis[1] <- mean(c(data$PRIMHARMBISSUWAKI.1., data$PRIMHARMPRIMSUWAKI.1..1, data$BISHARMBISSUWAKI.1., data$BISHARMBISSUWAKI.1..1), na.rm = TRUE)
srednieprimharmbis[2] <- mean(c(data$PRIMHARMBISSUWAKI.2., data$PRIMHARMPRIMSUWAKI.2..1, data$BISHARMBISSUWAKI.2., data$BISHARMBISSUWAKI.2..1), na.rm = TRUE)
srednieprimharmbis[3] <- mean(c(data$PRIMHARMBISSUWAKI.3., data$PRIMHARMPRIMSUWAKI.3..1, data$BISHARMBISSUWAKI.3., data$BISHARMBISSUWAKI.3..1), na.rm = TRUE)
srednieprimharmbis[4] <- mean(c(data$PRIMHARMBISSUWAKI.4., data$PRIMHARMPRIMSUWAKI.4..1, data$BISHARMBISSUWAKI.4., data$BISHARMBISSUWAKI.4..1), na.rm = TRUE)
srednieprimharmbis[5] <- mean(c(data$PRIMHARMBISSUWAKI.5., data$PRIMHARMPRIMSUWAKI.5..1, data$BISHARMBISSUWAKI.5., data$BISHARMBISSUWAKI.5..1), na.rm = TRUE)

srednieprimhelpprim <- numeric()
srednieprimhelpprim[1] <- mean(c(data$PRIMHELPPRIMSUWAKI.1., data$PRIMHELPPRIMSUWAKI.1..1), na.rm = TRUE)
srednieprimhelpprim[2] <- mean(c(data$PRIMHELPPRIMSUWAKI.2., data$PRIMHELPPRIMSUWAKI.2..1), na.rm = TRUE)
srednieprimhelpprim[3] <- mean(c(data$PRIMHELPPRIMSUWAKI.3., data$PRIMHELPPRIMSUWAKI.3..1), na.rm = TRUE)
srednieprimhelpprim[4] <- mean(c(data$PRIMHELPPRIMSUWAKI.4., data$PRIMHELPPRIMSUWAKI.4..1), na.rm = TRUE)
srednieprimhelpprim[5] <- mean(c(data$PRIMHELPPRIMSUWAKI.5., data$PRIMHELPPRIMSUWAKI.5..1), na.rm = TRUE)

srednieprimhelpbis <- numeric()
srednieprimhelpbis[1] <- mean(c(data$PRIMHELPBISSUWAKI.1., data$PRIMHELPBISSUWAKI.1..1), na.rm = TRUE)
srednieprimhelpbis[2] <- mean(c(data$PRIMHELPBISSUWAKI.2., data$PRIMHELPBISSUWAKI.2..1), na.rm = TRUE)
srednieprimhelpbis[3] <- mean(c(data$PRIMHELPBISSUWAKI.3., data$PRIMHELPBISSUWAKI.3..1), na.rm = TRUE)
srednieprimhelpbis[4] <- mean(c(data$PRIMHELPBISSUWAKI.4., data$PRIMHELPBISSUWAKI.4..1), na.rm = TRUE)
srednieprimhelpbis[5] <- mean(c(data$PRIMHELPBISSUWAKI.5., data$PRIMHELPBISSUWAKI.5..1), na.rm = TRUE)

sredniebishelpprim <- numeric()
sredniebishelpprim[1] <- mean(c(data$BISHELPPRIMSUWAKI.1., data$BISHELPPRIMSUWAKI.1..1), na.rm = TRUE)
sredniebishelpprim[2] <- mean(c(data$BISHELPPRIMSUWAKI.2., data$BISHELPPRIMSUWAKI.2..1), na.rm = TRUE)
sredniebishelpprim[3] <- mean(c(data$BISHELPPRIMSUWAKI.3., data$BISHELPPRIMSUWAKI.3..1), na.rm = TRUE)
sredniebishelpprim[4] <- mean(c(data$BISHELPPRIMSUWAKI.4., data$BISHELPPRIMSUWAKI.4..1), na.rm = TRUE)
sredniebishelpprim[5] <- mean(c(data$BISHELPPRIMSUWAKI.5., data$BISHELPPRIMSUWAKI.5..1), na.rm = TRUE)

sredniebishelpbis <- numeric()
sredniebishelpbis[1] <- mean(c(data$BISHELPBISSUWAKI.1., data$BISHELPBISSUWAKI.1..1), na.rm = TRUE)
sredniebishelpbis[2] <- mean(c(data$BISHELPBISSUWAKI.2., data$BISHELPBISSUWAKI.2..1), na.rm = TRUE)
sredniebishelpbis[3] <- mean(c(data$BISHELPBISSUWAKI.3., data$BISHELPBISSUWAKI.3..1), na.rm = TRUE)
sredniebishelpbis[4] <- mean(c(data$BISHELPBISSUWAKI.4., data$BISHELPBISSUWAKI.4..1), na.rm = TRUE)
sredniebishelpbis[5] <- mean(c(data$BISHELPBISSUWAKI.5., data$BISHELPBISSUWAKI.5..1), na.rm = TRUE)

sredniebisharmprim <- numeric()
sredniebisharmprim[1] <- mean(c(data$BISHARMPRIMSUWAKI.1., data$BISHARMPRIMSUWAKI.1..1), na.rm = TRUE)
sredniebisharmprim[2] <- mean(c(data$BISHARMPRIMSUWAKI.2., data$BISHARMPRIMSUWAKI.2..1), na.rm = TRUE)
sredniebisharmprim[3] <- mean(c(data$BISHARMPRIMSUWAKI.3., data$BISHARMPRIMSUWAKI.3..1), na.rm = TRUE)
sredniebisharmprim[4] <- mean(c(data$BISHARMPRIMSUWAKI.4., data$BISHARMPRIMSUWAKI.4..1), na.rm = TRUE)
sredniebisharmprim[5] <- mean(c(data$BISHARMPRIMSUWAKI.5., data$BISHARMPRIMSUWAKI.5..1), na.rm = TRUE)

sredniebisharmbis <- numeric()
sredniebisharmbis[1] <- mean(c(data2$r713q19.1., data2$BISHARMBISSUWAKI.A1.), na.rm = TRUE)
sredniebisharmbis[2] <- mean(c(data2$r713q19.2., data2$BISHARMBISSUWAKI.A2.), na.rm = TRUE)
sredniebisharmbis[3] <- mean(c(data2$r713q19.3., data2$BISHARMBISSUWAKI.A3.), na.rm = TRUE)
sredniebisharmbis[4] <- mean(c(data2$r713q19.4., data2$BISHARMBISSUWAKI.A4.), na.rm = TRUE)
sredniebisharmbis[5] <- mean(c(data2$r713q19.5., data2$BISHARMBISSUWAKI.A5.), na.rm = TRUE)

sredniekrukiwronybis <- numeric()
sredniekrukiwronybis[1] <- mean(c(data$BISKRUKIWRONYSUWAKI.1., data$BISKRUKIWRONYSUWAKI.1..1), na.rm=TRUE)
sredniekrukiwronybis[2] <- mean(c(data$BISKRUKIWRONYSUWAKI.2., data$BISKRUKIWRONYSUWAKI.2..1), na.rm=TRUE)
sredniekrukiwronybis[3] <- mean(c(data$BISKRUKIWRONYSUWAKI.3., data$BISKRUKIWRONYSUWAKI.3..1), na.rm=TRUE)
sredniekrukiwronybis[4] <- mean(c(data$BISKRUKIWRONYSUWAKI.4., data$BISKRUKIWRONYSUWAKI.4..1), na.rm=TRUE)
sredniekrukiwronybis[5] <- mean(c(data$BISKRUKIWRONYSUWAKI.5., data$BISKRUKIWRONYSUWAKI.5..1), na.rm=TRUE)

srednienotkrukiwronybis <- numeric()
srednienotkrukiwronybis[1] <- mean(c(data$BISNOTKRUKIWRONYSUWA.1., data$BISNOTKRUKIWRONYSUWA.1..1), na.rm=TRUE)
srednienotkrukiwronybis[2] <- mean(c(data$BISNOTKRUKIWRONYSUWA.2., data$BISNOTKRUKIWRONYSUWA.2..1), na.rm=TRUE)
srednienotkrukiwronybis[3] <- mean(c(data$BISNOTKRUKIWRONYSUWA.3., data$BISNOTKRUKIWRONYSUWA.3..1), na.rm=TRUE)
srednienotkrukiwronybis[4] <- mean(c(data$BISNOTKRUKIWRONYSUWA.4., data$BISNOTKRUKIWRONYSUWA.4..1), na.rm=TRUE)
srednienotkrukiwronybis[5] <- mean(c(data$BISNOTKRUKIWRONYSUWA.5., data$BISNOTKRUKIWRONYSUWA.5..1), na.rm=TRUE)

## LEGENDA do factorów: 
## 1 - ZMIANA -> BRAK ZMIANY -> ZMIANA (¯Ó£TY)
## 2 - BRAK ZMIANY -> ZMIANA -> ZMIANA (NIEBIESKI)
## 3 - ZMIANA -> ZMIANA -> BRAK ZMIANY (CZARNY)
## 4 - BRAK ZMIANY -> BRAK ZMIANY -> ZMIANA (FIOLETOWY)
## 5 - ZMIANA -> BRAK ZMIANY -> BRAK ZMIANY (SZARY)
## 6 - BRAK ZMIANY -> ZMIANA -> BRAK ZMIANY (ZIELONY)

primharmprimfactor <- c(1,2,3,4,5)
primharmbisfactor <- c(6,5,4,3,2)
primhelpprimfactor <- c(1,6,5,4,4)
primhelpbisfactor <- c(6,1,2,3,1)
n <- c(1,2,3,4,5,1,2,3,4,5)
m <- c(1,1,1,1,1,2,2,2,2,2)

#LEGENDA do factorów moralnych

primharmprimmoralfactor <- c()
primharmbismoralfactor <- c()
primhelpprimmoralfactor <- c()
primhelpbismoralfactor <- c()


dataframe <- data.frame(numer = n, srednia = c(srednieprimharmprim, srednieprimharmbis), z = m, f=c(primharmprimfactor, primharmbisfactor))
plot(dataframe$numer, dataframe$srednia, col=c("yellow1","blue","black","violet","grey","darkgreen")[dataframe$f], pch=c(3, 4)[dataframe$z], xlab = "Pytanie", ylab ="Œrednia", lwd=3, main = "HARM PRIM VS HARM BIS")
dev.copy(png,'primharmprimbis.png')
dev.off()

dataframe2 <- data.frame(numer = n, srednia = c(srednieprimhelpprim, srednieprimhelpbis), z = m, f=c(primhelpprimfactor, primhelpbisfactor))
plot(dataframe2$numer, dataframe2$srednia, col=c("yellow1","blue","black","violet","grey","darkgreen")[dataframe2$f], pch=c(3, 4)[dataframe2$z], xlab = "Pytanie", ylab ="Œrednia", lwd=3, main = "HELP PRIM VS HELP BIS")
dev.copy(png,'primhelpprimsbis.png')
dev.off()

dataframe3 <- data.frame(numer = n, srednia = c(srednieprimharmprim, srednieprimhelpprim), z = m, f=c(primharmprimfactor, primhelpprimfactor))
plot(dataframe3$numer, dataframe3$srednia, col=c("yellow1","blue","black","violet","grey","darkgreen")[dataframe3$f], pch=c(25, 24)[dataframe3$z], xlab = "Pytanie", ylab ="Œrednia", lwd=3, main = "HARM PRIM VS HELP PRIM")
dev.copy(png,'primharmhelpprim.png')
dev.off()

dataframe4 <- data.frame(numer = n, srednia = c(srednieprimharmbis, srednieprimhelpbis), z = m, f=c(primharmbisfactor, primhelpbisfactor))
plot(dataframe4$numer, dataframe4$srednia, col=c("yellow1","blue","black","violet","grey","darkgreen")[dataframe4$f], pch=c(25, 24)[dataframe4$z], xlab = "Pytanie", ylab ="Œrednia", lwd=3, main = "HARM BIS VS HELP BIS")
dev.copy(png,'primharmhelpbis.png')
dev.off()

dataframe5 <- data.frame(numer = n, srednia =c(sredniebishelpprim, sredniebishelpbis))
plot(dataframe5$numer, dataframe5$srednia, type="n", main="Zachowanie dyrektora HELP")
points(sredniebishelpprim, col ="red")
points(sredniebishelpbis, col ="blue")
dev.copy(png,'dyrektorhelp.png')
dev.off()

dataframe6 <- data.frame(numer = n, srednia =c(sredniebisharmprim, sredniebisharmbis))
plot(dataframe6$numer, dataframe6$srednia, type="n", main="Zachowanie dyrektora HARM")
points(sredniebisharmprim, col ="red")
points(sredniebisharmbis, col ="blue")
dev.copy(png,'dyrektorharm.png')
dev.off()

dataframe7 <- data.frame(numer = n, srednia =c(sredniebishelpprim, sredniebisharmbis))
plot(dataframe7$numer, dataframe7$srednia, type="n", main="Zachowanie dyrektora HARM vs HELP")
points(sredniebishelpprim, col ="blue", lwd=3, pch=dataframe8$o[dataframe8$numer])
points(sredniebisharmprim, col ="red", lwd=3, pch=dataframe8$m[dataframe8$numer])
par(col="red")
abline(mean(sredniebisharmprim),0, lty = 2)
par(col="blue")
abline(mean(sredniebishelpprim),0, lty = 2)

dev.copy(png,'dyrektorharmvshelpplus.png')
dev.off()

## 1. Jeœli ostatnie ogniwo jest pozytywnie moralnie to poziom przyczynienia siê jest mniejszy dla wszystkich ogniw, oprócz zakazu
## 2. Najbardziej od œredniej odbiegaj¹ pi¹tki, które s¹ mocno nacechowane moralnie.

dataframe8 <- data.frame(numer = n, srednia =c(sredniebishelpbis, sredniebisharmbis), m=c(25, 25, 1, 24, 24), o=c(24, 24, 1, 25, 25))
par(col="darkgreen")
plot(dataframe8$numer, dataframe8$srednia, type="n", main="Zachowanie dyrektora HARM vs HELP", ylab="Przyczynienie", xlab="Ogniwo ³añcucha")
points(sredniebishelpbis, col ="blue", lwd=3, pch=dataframe8$m[dataframe8$numer])
points(sredniebisharmbis, col ="red", lwd=3, pch= dataframe8$o[dataframe8$numer])
par(col="red")
abline(mean(sredniebisharmbis),0, lty=2)
par(col="blue")
abline(mean(sredniebishelpbis),0, lty=2)
par(col="black")
legend("topleft", legend =c("Positive", "Negative", "Harm", "Help"), lwd = 2, pch=(c(24, 25, 0, 0)), col=c("black", "black", "red", "blue"))
dev.copy(png,'dyrektorharmvshelpminus.png')

plot(1:5, c(1.5,2,2,3,3.5), type="n")
points(srednienotkrukiwronybis, col="blue")
points(sredniekrukiwronybis, col="red")